name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Ploogly Release Build - Windows
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ploogly-windows
        path: target/release/ploogly.exe

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Ploogly Release Build - Linux-GNU
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ploogly-linux-gnu
        path: target/release/ploogly
